# 기본적 데이터 전처리

In [3]:
'''
import numpy as np
import pandas as pd 
import matplotlib.pyplot as plt

test = pd.read_csv("house/test.csv")
train = pd.read_csv("house/train.csv")
test['TrainSplit'] = 'test'
train['TrainSplit'] = 'train'

total = train.append(test)

for a in ['MSZoning','Utilities','Electrical','Functional','SaleType']:
    total[a].fillna(total[a].value_counts().idxmax(), inplace=True)
    
    
for a in total.select_dtypes('object').columns:
    if 'Bsmt'  in a:
        total[a].fillna('empty',inplace = True)
for a in total.columns:
    if 'Bsmt' in a:
        total[a].fillna(0.0,inplace = True)   
        
for a in total.select_dtypes('object').columns:
    if 'Garage' in a:
        total[a].fillna('empty',inplace = True)
        

        
filter_bsmtcolumns = [col for col in total.columns  if 'Bsmt' in col]
basement = total.loc[:, filter_bsmtcolumns].copy()
garage = total.loc[:,'GarageType':'GarageCond'].copy()

total.dropna(subset=['GarageArea'], inplace=True)
total.dropna(subset=['Exterior1st'], inplace=True)
total['FireplaceQu'].loc[total['Fireplaces']==0] = 'empty'

total.set_index('Id', inplace=True)

Mapping_values = {
    'Ex' :5,
    'Gd' :4,
    'TA' :3,
    'Fa' :2,
    'Po' :1,    
    'empty' :0,
    'GdPrv': 4,
       'MnPrv': 3,
       'GdWo': 2,
       'MnWw': 1,
       'NA': 0,
    'Fin':3,
       'RFn':2 ,
       'Unf':1,
    'Y':1,
    'N':0,
    'GLQ':6,
       'ALQ':5,
       'BLQ':4,
       'Rec':3,
       'LwQ':2,
       'Unf':1,
       'NA':0,
    'Av':3,
       'Mn':2,
       'No':1,
       'NA':0,
}
total.replace(Mapping_values,inplace=True)
total['PoolQC'].fillna(0, inplace= True)
total['Fence'].fillna(0, inplace= True)

lotmean = np.around(total['LotFrontage'].mean())
total['LotFrontage'].fillna(lotmean, inplace=True)

total['MasVnrType'].fillna('None', inplace=True)
total['MasVnrArea'].fillna(0.0, inplace=True)

total.drop(['GarageYrBlt'], axis=1, inplace=True)
'''
# 데이터 전처리의 전처리 끝 : 제출 전 답지 

import numpy as np
import pandas as pd 
import matplotlib.pyplot as plt

test = pd.read_csv("house/test.csv")
train = pd.read_csv("house/train.csv")
test['TrainSplit'] = 'test'
train['TrainSplit'] = 'train'

total = train.append(test)

total.set_index('Id', inplace=True)

for a in ['MSZoning','Utilities','Electrical','Functional','SaleType']:
    total[a].fillna(total[a].value_counts().idxmax(), inplace=True)
for a in range(1, len(total.index)):
    if total.loc[a,'MSSubClass'] == 120 or total.loc[a,'MSSubClass'] == 150 or total.loc[a,'MSSubClass'] == 160 or total.loc[a,'MSSubClass'] == 180:
        total.loc[a,'MSSub'] = 1
    else:
        total.loc[a,'MSSub'] = 0
        
for a in range(1, len(total.index)):
    if total.loc[a,'Fence'] == 'GdPrv':
        total.loc[a,'Fence_Prv'] = 2
        total.loc[a,'Fence_Wire'] = 0
    elif total.loc[a,'Fence'] == 'MnPrv':
        total.loc[a,'Fence_Prv'] = 1
        total.loc[a,'Fence_Wire'] = 0
    elif total.loc[a,'Fence'] == 'GdWo':
        total.loc[a,'Fence_Wire'] = 2
        total.loc[a,'Fence_Prv'] = 0        
    elif total.loc[a,'Fence'] == 'MnWw':
        total.loc[a,'Fence_Wire'] = 1
        total.loc[a,'Fence_Prv'] = 0        
    else:
        total.loc[a,'Fence_Wire'] = 0
        total.loc[a,'Fence_Wire'] = 0
    
total['BsmtBath'] = total['BsmtFullBath'] + total['BsmtHalfBath'] /2

total['Bath'] = total['FullBath'] + total['HalfBath'] /2

total.drop(['BsmtFullBath','FullBath','BsmtHalfBath','BsmtHalfBath','MSSubClass'], axis=1, inplace=True)


total['Fence_Prv'].fillna(0, inplace=True)
total['Fence_Wire'].fillna(0, inplace=True)
    
total.drop(['Fence'], axis=1, inplace=True)
    
for a in total.select_dtypes('object').columns:
    if 'Bsmt'  in a:
        total[a].fillna('empty',inplace = True)
for a in total.columns:
    if 'Bsmt' in a:
        total[a].fillna(0.0,inplace = True)   
        
for a in total.select_dtypes('object').columns:
    if 'Garage' in a:
        total[a].fillna('empty',inplace = True)
        

        
filter_bsmtcolumns = [col for col in total.columns  if 'Bsmt' in col]
basement = total.loc[:, filter_bsmtcolumns].copy()
garage = total.loc[:,'GarageType':'GarageCond'].copy()

total.dropna(subset=['GarageArea'], inplace=True)
total.dropna(subset=['Exterior1st'], inplace=True)
total['FireplaceQu'].loc[total['Fireplaces']==0] = 'empty'


Mapping_values = {
    'Ex' :5,
    'Gd' :4,
    'TA' :3,
    'Fa' :2,
    'Po' :1,    
    'empty' :0,
    'Fin':3,
       'RFn':2 ,
       'Unf':1,
    'Y':1,
    'N':0,
    'GLQ':6,
       'ALQ':5,
       'BLQ':4,
       'Rec':3,
       'LwQ':2,
       'Unf':1,
       'NA':0,
    'Av':3,
       'Mn':2,
       'No':1,
       'NA':0,
        'AllPub':4,
       'NoSewr':3,
       'NoSeWa':2,
       'ELO':1,
       'Reg':3,
       'IR1':2,
       'IR2':1,
       'IR3':0,
       'Gtl':0,
       'Mod':1,
       'Sev':2,
}
total.replace(Mapping_values,inplace=True)
total['PoolQC'].fillna(0, inplace= True)

lotmean = np.around(total['LotFrontage'].mean())
total['LotFrontage'].fillna(lotmean, inplace=True)

total['MasVnrType'].fillna('None', inplace=True)
total['MasVnrArea'].fillna(0.0, inplace=True)

total.drop(['GarageYrBlt'], axis=1, inplace=True)
#정답 포함

C:\ProgramData\Anaconda3\lib\site-packages\pandas\core\indexing.py:1637: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_single_block(indexer, value, name)

In [ ]:
filtered_cols = [a for a in total.columns if total[a].isnull().sum() != 0]
for a in filtered_cols:
    print(a)
    print(total[a].value_counts())
    print(total[a].value_counts().sum())    
    print('----------------------------------')

## 데이터 분할

In [4]:
total.drop(['TrainSplit'],axis=1, inplace=True) #total = train+test+SalePrice
df = total.drop(['SalePrice'], axis=1) # 세일가격 없는 전체 세트

## 피쳐 스케일링

### one-hot encoding

In [5]:
df = pd.get_dummies(df, prefix=df.select_dtypes('object').columns)

In [6]:
df

,LotFrontage,LotArea,LotShape,Utilities,LandSlope,OverallQual,OverallCond,YearBuilt,YearRemodAdd,MasVnrArea,...,SaleType_ConLw,SaleType_New,SaleType_Oth,SaleType_WD,SaleCondition_Abnorml,SaleCondition_AdjLand,SaleCondition_Alloca,SaleCondition_Family,SaleCondition_Normal,SaleCondition_Partial
Id,,,,,,,,,,,,,,,,,,,,,
1,65.0,8450,3,4,0,7,5,2003,2003,196.0,...,0,0,0,1,0,0,0,0,1,0
2,80.0,9600,3,4,0,6,8,1976,1976,0.0,...,0,0,0,1,0,0,0,0,1,0
3,68.0,11250,2,4,0,7,5,2001,2002,162.0,...,0,0,0,1,0,0,0,0,1,0
4,60.0,9550,2,4,0,7,5,1915,1970,0.0,...,0,0,0,1,1,0,0,0,0,0
5,84.0,14260,2,4,0,8,5,2000,2000,350.0,...,0,0,0,1,0,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2915,21.0,1936,3,4,0,4,7,1970,1970,0.0,...,0,0,0,1,0,0,0,0,1,0
2916,21.0,1894,3,4,0,4,5,1970,1970,0.0,...,0,0,0,1,1,0,0,0,0,0
2917,160.0,20000,3,4,0,5,7,1960,1996,0.0,...,0,0,0,1,1,0,0,0,0,0
2918,62.0,10441,3,4,0,5,5,1992,1992,0.0,...,0,0,0,1,0,0,0,0,1,0
2919,74.0,9627,3,4,1,7,5,1993,1994,94.0,...,0,0,0,1,0,0,0,0,1,0

### MinMaxScaler

In [7]:
from sklearn.preprocessing import MinMaxScaler
mms = MinMaxScaler()
df_scaled = mms.fit_transform(df)

In [8]:
dataf = pd.DataFrame(df_scaled, columns = df.columns)

In [9]:
train = dataf.iloc[:1460,:] 
test = dataf.iloc[1460:,:] 


train_target = total.loc[:1460,'SalePrice'] #train 세일가격
test_target = total.loc[1461:,'SalePrice']  #test 세일가격 =>정답지

In [10]:
dataf.iloc[:1460,:].shape

(1460, 229)

In [11]:
print(train.shape, test.shape, train_target.shape, test_target.shape)

(1460, 229) (1457, 229) (1460,) (1457,)

In [12]:
print("무야호~")

무야호~

## 기초 선형 회귀

In [26]:
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split as tts

X_train, X_test, y_train, y_test = tts(
    train, train_target, shuffle=True, random_state=11, test_size=0.2)

print(X_train.shape, X_test.shape)

(1168, 229) (292, 229)

In [21]:
from sklearn.linear_model import LinearRegression
lr = LinearRegression()
lr.fit(X_train, y_train)

LinearRegression()

In [22]:
y_test_pred = lr.predict(X_test)

In [25]:
lr.score(X_train, y_train)

0.9262035927044544

In [24]:
lr.score(X_test, y_test)

-5.880291185722761e+19